window.ROUTE_MAP_DATA = {
    "version": 1,
    "generatedAt": "2026-05-22T19:50:39+00:00",
    "source": {
        "rooms": "rooms.a80",
        "roomsDir": "rooms_unpacked",
        "routeTable": "enemies.route.a80",
        "logicDir": "logic"
    },
    "room": {
        "amountX": 7,
        "amountY": 4,
        "width": 32,
        "height": 22
    },
    "rooms": [
        {
            "id": "0,0",
            "x": 0,
            "y": 0,
            "file": "rooms_unpacked/room0,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "1,0",
            "x": 1,
            "y": 0,
            "file": "rooms_unpacked/room1,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "2,0",
            "x": 2,
            "y": 0,
            "file": "rooms_unpacked/room2,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "3,0",
            "x": 3,
            "y": 0,
            "file": "rooms_unpacked/room3,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "4,0",
            "x": 4,
            "y": 0,
            "file": "rooms_unpacked/room4,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "5,0",
            "x": 5,
            "y": 0,
            "file": "rooms_unpacked/room5,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "6,0",
            "x": 6,
            "y": 0,
            "file": "rooms_unpacked/room6,0.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "0,1",
            "x": 0,
            "y": 1,
            "file": "rooms_unpacked/room0,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "1,1",
            "x": 1,
            "y": 1,
            "file": "rooms_unpacked/room1,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "2,1",
            "x": 2,
            "y": 1,
            "file": "rooms_unpacked/room2,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "3,1",
            "x": 3,
            "y": 1,
            "file": "rooms_unpacked/room3,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "4,1",
            "x": 4,
            "y": 1,
            "file": "rooms_unpacked/room4,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "5,1",
            "x": 5,
            "y": 1,
            "file": "rooms_unpacked/room5,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "6,1",
            "x": 6,
            "y": 1,
            "file": "rooms_unpacked/room6,1.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "0,2",
            "x": 0,
            "y": 2,
            "file": "rooms_unpacked/room0,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "1,2",
            "x": 1,
            "y": 2,
            "file": "rooms_unpacked/room1,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "2,2",
            "x": 2,
            "y": 2,
            "file": "rooms_unpacked/room2,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "3,2",
            "x": 3,
            "y": 2,
            "file": "rooms_unpacked/room3,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "4,2",
            "x": 4,
            "y": 2,
            "file": "rooms_unpacked/room4,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "5,2",
            "x": 5,
            "y": 2,
            "file": "rooms_unpacked/room5,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "6,2",
            "x": 6,
            "y": 2,
            "file": "rooms_unpacked/room6,2.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "0,3",
            "x": 0,
            "y": 3,
            "file": "rooms_unpacked/room0,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "1,3",
            "x": 1,
            "y": 3,
            "file": "rooms_unpacked/room1,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "2,3",
            "x": 2,
            "y": 3,
            "file": "rooms_unpacked/room2,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "3,3",
            "x": 3,
            "y": 3,
            "file": "rooms_unpacked/room3,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "4,3",
            "x": 4,
            "y": 3,
            "file": "rooms_unpacked/room4,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "5,3",
            "x": 5,
            "y": 3,
            "file": "rooms_unpacked/room5,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        },
        {
            "id": "6,3",
            "x": 6,
            "y": 3,
            "file": "rooms_unpacked/room6,3.atr",
            "exists": true,
            "bytes": 768,
            "hasFullRoomData": true
        }
    ],
    "tableOrder": [
        "route_0_0_left",
        "route_0_0_mid_left",
        "route_0_0_mid_right",
        "route_0_0_right",
        "route_0_0_basement_end",
        "route_0_0_right_entry",
        "route_0_1_right_entry",
        "route_0_1_right_mid",
        "route_0_1_mid",
        "route_0_1_left_mid",
        "route_0_1_bottom_entry",
        "route_0_2_top_entry",
        "route_0_2_upper_left",
        "route_0_2_mid_left",
        "route_0_2_lower_left",
        "route_0_2_lower_right",
        "route_0_2_mid_right",
        "route_0_2_upper_right",
        "route_1_0_left_entry",
        "route_1_0_arch",
        "route_1_0_lower_walk",
        "route_1_0_right_entry",
        "route_1_1_left_entry",
        "route_1_1_left_mid",
        "route_1_1_left_inner",
        "route_1_1_left_jump_right",
        "route_1_1_right_entry",
        "route_1_1_right_mid",
        "route_1_1_right_jump_left",
        "route_2_0_left_entry",
        "route_2_0_top_left",
        "route_2_0_top_mid",
        "route_2_0_top_right_entry",
        "route_2_0_basement_entry",
        "route_2_0_basement_mid",
        "route_2_0_basement_end",
        "route_2_0_basement_jump",
        "route_2_1_left_entry",
        "route_2_1_left_mid",
        "route_2_1_right_entry",
        "route_2_1_right_top_entry",
        "route_2_1_right_mid",
        "route_2_1_elevator_jump_left",
        "route_3_0_left_entry",
        "route_3_0_left_drop",
        "route_3_1_top_entry",
        "route_3_1_ledge_fork",
        "route_3_1_top_left_entry",
        "route_3_1_bottom_fork",
        "route_3_1_left_entry",
        "route_3_1_before_hole_fork",
        "route_3_1_bottom_jump_right",
        "route_3_1_elevator_wait",
        "route_3_1_elevator_top_jump_left",
        "route_3_1_right_jump_left",
        "route_3_1_right_entry",
        "route_4_1_left_entry",
        "route_4_1_left_mid",
        "route_4_1_left_jump",
        "route_4_1_elevator_wait",
        "route_4_1_elevator_top",
        "route_4_1_right_mid",
        "route_4_1_right_entry",
        "route_4_2_top_landing",
        "route_4_2_slope_mid",
        "route_4_2_slope_right",
        "route_4_2_lower_right",
        "route_4_2_lower_left",
        "route_4_2_bottom_mid",
        "route_5_1_left_entry",
        "route_5_1_bottom_left",
        "route_5_1_bottom_fork",
        "route_5_1_bottom_right",
        "route_5_1_right_entry",
        "route_6_1_left_entry",
        "route_6_1_left_jump_low",
        "route_6_1_left_ledge_low",
        "route_6_1_left_ledge_mid",
        "route_6_1_left_ledge_high",
        "route_6_1_red_door_left",
        "route_6_1_red_door_fall",
        "route_6_1_left_return_entry"
    ],
    "includeFiles": [
        "enemies.route_0_0.a80",
        "enemies.route_0_1.a80",
        "enemies.route_0_2.a80",
        "enemies.route_1_0.a80",
        "enemies.route_1_1.a80",
        "enemies.route_2_0.a80",
        "enemies.route_2_1.a80",
        "enemies.route_3_0.a80",
        "enemies.route_3_1.a80",
        "enemies.route_4_1.a80",
        "enemies.route_4_2.a80",
        "enemies.route_5_1.a80",
        "enemies.route_6_1.a80",
        "enemies.route_6_2.a80",
        "enemies.route_6_3.a80"
    ],
    "points": [
        {
            "id": "route_0_0_left",
            "roomX": 0,
            "roomY": 0,
            "x": 4,
            "y": 9,
            "type": "normal",
            "topLeft": "route_0_0_mid_left",
            "bottomRight": "route_0_0_mid_left",
            "alternative": null,
            "sourceFile": "enemies.route_0_0.a80",
            "sourceLine": 1
        },
        {
            "id": "route_0_0_mid_left",
            "roomX": 0,
            "roomY": 0,
            "x": 12,
            "y": 10,
            "type": "normal",
            "topLeft": "route_0_0_left",
            "bottomRight": "route_0_0_mid_right",
            "alternative": null,
            "sourceFile": "enemies.route_0_0.a80",
            "sourceLine": 13
        },
        {
            "id": "route_0_0_mid_right",
            "roomX": 0,
            "roomY": 0,
            "x": 20,
            "y": 9,
            "type": "normal",
            "topLeft": "route_0_0_mid_left",
            "bottomRight": "route_0_0_right",
            "alternative": null,
            "sourceFile": "enemies.route_0_0.a80",
            "sourceLine": 25
        },
        {
            "id": "route_0_0_right",
            "roomX": 0,
            "roomY": 0,
            "x": 27,
            "y": 9,
            "type": "normal",
            "topLeft": "route_0_0_mid_right",
            "bottomRight": "route_0_0_right_entry",
            "alternative": "route_0_0_basement_end",
            "sourceFile": "enemies.route_0_0.a80",
            "sourceLine": 37
        },
        {
            "id": "route_0_0_basement_end",
            "roomX": 0,
            "roomY": 0,
            "x": 20,
            "y": 16,
            "type": "normal",
            "topLeft": "route_0_0_right",
            "bottomRight": "route_0_0_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_0.a80",
            "sourceLine": 49
        },
        {
            "id": "route_0_0_right_entry",
            "roomX": 0,
            "roomY": 0,
            "x": 31,
            "y": 5,
            "type": "exit",
            "topLeft": "route_0_0_basement_end",
            "bottomRight": "route_1_0_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_0.a80",
            "sourceLine": 61
        },
        {
            "id": "route_0_1_right_entry",
            "roomX": 0,
            "roomY": 1,
            "x": 31,
            "y": 19,
            "type": "exit",
            "topLeft": "route_0_1_right_mid",
            "bottomRight": "route_1_1_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_0_1_right_mid",
            "roomX": 0,
            "roomY": 1,
            "x": 24,
            "y": 19,
            "type": "normal",
            "topLeft": "route_0_1_mid",
            "bottomRight": "route_0_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_0_1_mid",
            "roomX": 0,
            "roomY": 1,
            "x": 18,
            "y": 19,
            "type": "normal",
            "topLeft": "route_0_1_left_mid",
            "bottomRight": "route_0_1_right_mid",
            "alternative": null,
            "sourceFile": "enemies.route_0_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_0_1_left_mid",
            "roomX": 0,
            "roomY": 1,
            "x": 11,
            "y": 19,
            "type": "normal",
            "topLeft": "route_0_1_mid",
            "bottomRight": "route_0_1_bottom_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_0_1_bottom_entry",
            "roomX": 0,
            "roomY": 1,
            "x": 4,
            "y": 21,
            "type": "exit",
            "topLeft": "route_0_1_left_mid",
            "bottomRight": "route_0_2_top_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_0_2_top_entry",
            "roomX": 0,
            "roomY": 2,
            "x": 4,
            "y": 0,
            "type": "exit",
            "topLeft": "route_0_1_bottom_entry",
            "bottomRight": "route_0_2_upper_left",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 1
        },
        {
            "id": "route_0_2_upper_left",
            "roomX": 0,
            "roomY": 2,
            "x": 5,
            "y": 3,
            "type": "normal",
            "topLeft": "route_0_2_top_entry",
            "bottomRight": "route_0_2_mid_left",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 13
        },
        {
            "id": "route_0_2_mid_left",
            "roomX": 0,
            "roomY": 2,
            "x": 3,
            "y": 11,
            "type": "normal",
            "topLeft": "route_0_2_upper_left",
            "bottomRight": "route_0_2_lower_left",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 25
        },
        {
            "id": "route_0_2_lower_left",
            "roomX": 0,
            "roomY": 2,
            "x": 11,
            "y": 18,
            "type": "normal",
            "topLeft": "route_0_2_mid_left",
            "bottomRight": "route_0_2_lower_right",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 37
        },
        {
            "id": "route_0_2_lower_right",
            "roomX": 0,
            "roomY": 2,
            "x": 26,
            "y": 17,
            "type": "normal",
            "topLeft": "route_0_2_lower_left",
            "bottomRight": "route_0_2_mid_right",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 49
        },
        {
            "id": "route_0_2_mid_right",
            "roomX": 0,
            "roomY": 2,
            "x": 27,
            "y": 10,
            "type": "normal",
            "topLeft": "route_0_2_lower_right",
            "bottomRight": "route_0_2_upper_right",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 61
        },
        {
            "id": "route_0_2_upper_right",
            "roomX": 0,
            "roomY": 2,
            "x": 26,
            "y": 4,
            "type": "normal",
            "topLeft": "route_0_2_mid_right",
            "bottomRight": "route_0_2_top_entry",
            "alternative": null,
            "sourceFile": "enemies.route_0_2.a80",
            "sourceLine": 73
        },
        {
            "id": "route_1_0_left_entry",
            "roomX": 1,
            "roomY": 0,
            "x": 0,
            "y": 5,
            "type": "exit",
            "topLeft": "route_0_0_right_entry",
            "bottomRight": "route_1_0_arch",
            "alternative": null,
            "sourceFile": "enemies.route_1_0.a80",
            "sourceLine": 1
        },
        {
            "id": "route_1_0_arch",
            "roomX": 1,
            "roomY": 0,
            "x": 10,
            "y": 3,
            "type": "normal",
            "topLeft": "route_1_0_left_entry",
            "bottomRight": "route_1_0_lower_walk",
            "alternative": null,
            "sourceFile": "enemies.route_1_0.a80",
            "sourceLine": 13
        },
        {
            "id": "route_1_0_lower_walk",
            "roomX": 1,
            "roomY": 0,
            "x": 20,
            "y": 13,
            "type": "normal",
            "topLeft": "route_1_0_arch",
            "bottomRight": "route_1_0_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_1_0.a80",
            "sourceLine": 25
        },
        {
            "id": "route_1_0_right_entry",
            "roomX": 1,
            "roomY": 0,
            "x": 31,
            "y": 7,
            "type": "exit",
            "topLeft": "route_1_0_lower_walk",
            "bottomRight": "route_2_0_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_1_0.a80",
            "sourceLine": 37
        },
        {
            "id": "route_1_1_left_entry",
            "roomX": 1,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_0_1_right_entry",
            "bottomRight": "route_1_1_left_mid",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_1_1_left_mid",
            "roomX": 1,
            "roomY": 1,
            "x": 7,
            "y": 19,
            "type": "normal",
            "topLeft": "route_1_1_left_entry",
            "bottomRight": "route_1_1_left_inner",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_1_1_left_inner",
            "roomX": 1,
            "roomY": 1,
            "x": 13,
            "y": 19,
            "type": "normal",
            "topLeft": "route_1_1_left_mid",
            "bottomRight": "route_1_1_left_mid",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_1_1_left_jump_right",
            "roomX": 1,
            "roomY": 1,
            "x": 18,
            "y": 19,
            "type": "jump_right",
            "topLeft": "route_1_1_left_inner",
            "bottomRight": "route_1_1_right_mid",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_1_1_right_entry",
            "roomX": 1,
            "roomY": 1,
            "x": 31,
            "y": 19,
            "type": "exit",
            "topLeft": "route_1_1_right_mid",
            "bottomRight": "route_2_1_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_1_1_right_mid",
            "roomX": 1,
            "roomY": 1,
            "x": 26,
            "y": 19,
            "type": "normal",
            "topLeft": "route_1_1_right_entry",
            "bottomRight": "route_1_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 61
        },
        {
            "id": "route_1_1_right_jump_left",
            "roomX": 1,
            "roomY": 1,
            "x": 20,
            "y": 19,
            "type": "jump_left",
            "topLeft": "route_1_1_left_inner",
            "bottomRight": "route_1_1_right_mid",
            "alternative": null,
            "sourceFile": "enemies.route_1_1.a80",
            "sourceLine": 73
        },
        {
            "id": "route_2_0_left_entry",
            "roomX": 2,
            "roomY": 0,
            "x": 0,
            "y": 7,
            "type": "exit",
            "topLeft": "route_1_0_right_entry",
            "bottomRight": "route_2_0_top_left",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 1
        },
        {
            "id": "route_2_0_top_left",
            "roomX": 2,
            "roomY": 0,
            "x": 8,
            "y": 7,
            "type": "normal",
            "topLeft": "route_2_0_left_entry",
            "bottomRight": "route_2_0_top_mid",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 13
        },
        {
            "id": "route_2_0_top_mid",
            "roomX": 2,
            "roomY": 0,
            "x": 17,
            "y": 7,
            "type": "normal",
            "topLeft": "route_2_0_top_left",
            "bottomRight": "route_2_0_top_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 25
        },
        {
            "id": "route_2_0_top_right_entry",
            "roomX": 2,
            "roomY": 0,
            "x": 31,
            "y": 7,
            "type": "exit",
            "topLeft": "route_2_0_top_mid",
            "bottomRight": "route_3_0_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 37
        },
        {
            "id": "route_2_0_basement_entry",
            "roomX": 2,
            "roomY": 0,
            "x": 21,
            "y": 12,
            "type": "normal",
            "topLeft": "route_2_0_top_mid",
            "bottomRight": "route_2_0_basement_mid",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 49
        },
        {
            "id": "route_2_0_basement_mid",
            "roomX": 2,
            "roomY": 0,
            "x": 15,
            "y": 16,
            "type": "normal",
            "topLeft": "route_2_0_basement_entry",
            "bottomRight": "route_2_0_basement_end",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 61
        },
        {
            "id": "route_2_0_basement_end",
            "roomX": 2,
            "roomY": 0,
            "x": 6,
            "y": 16,
            "type": "normal",
            "topLeft": "route_2_0_basement_mid",
            "bottomRight": "route_2_0_basement_jump",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 73
        },
        {
            "id": "route_2_0_basement_jump",
            "roomX": 2,
            "roomY": 0,
            "x": 21,
            "y": 12,
            "type": "jump_right",
            "topLeft": "route_2_0_basement_end",
            "bottomRight": "route_2_0_top_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_2_0.a80",
            "sourceLine": 85
        },
        {
            "id": "route_2_1_left_entry",
            "roomX": 2,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_1_1_right_entry",
            "bottomRight": "route_2_1_left_mid",
            "alternative": null,
            "sourceFile": "enemies.route_2_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_2_1_left_mid",
            "roomX": 2,
            "roomY": 1,
            "x": 7,
            "y": 19,
            "type": "normal",
            "topLeft": "route_2_1_left_entry",
            "bottomRight": "route_2_1_elevator_jump_left",
            "alternative": null,
            "sourceFile": "enemies.route_2_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_2_1_right_entry",
            "roomX": 2,
            "roomY": 1,
            "x": 31,
            "y": 19,
            "type": "exit",
            "topLeft": "route_2_1_right_mid",
            "bottomRight": "route_3_1_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_2_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_2_1_right_top_entry",
            "roomX": 2,
            "roomY": 1,
            "x": 31,
            "y": 7,
            "type": "exit",
            "topLeft": "route_3_1_top_left_entry",
            "bottomRight": "route_3_1_top_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_2_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_2_1_right_mid",
            "roomX": 2,
            "roomY": 1,
            "x": 24,
            "y": 19,
            "type": "normal",
            "topLeft": "route_2_1_elevator_jump_left",
            "bottomRight": "route_2_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_2_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_2_1_elevator_jump_left",
            "roomX": 2,
            "roomY": 1,
            "x": 20,
            "y": 19,
            "type": "jump_left",
            "topLeft": "route_2_1_left_mid",
            "bottomRight": "route_2_1_right_mid",
            "alternative": null,
            "sourceFile": "enemies.route_2_1.a80",
            "sourceLine": 61
        },
        {
            "id": "route_3_0_left_entry",
            "roomX": 3,
            "roomY": 0,
            "x": 0,
            "y": 7,
            "type": "exit",
            "topLeft": "route_2_0_top_right_entry",
            "bottomRight": "route_3_0_left_drop",
            "alternative": null,
            "sourceFile": "enemies.route_3_0.a80",
            "sourceLine": 1
        },
        {
            "id": "route_3_0_left_drop",
            "roomX": 3,
            "roomY": 0,
            "x": 2,
            "y": 21,
            "type": "normal",
            "topLeft": "route_3_0_left_entry",
            "bottomRight": "route_3_1_top_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_0.a80",
            "sourceLine": 13
        },
        {
            "id": "route_3_1_top_entry",
            "roomX": 3,
            "roomY": 1,
            "x": 2,
            "y": 0,
            "type": "normal",
            "topLeft": "route_3_0_left_drop",
            "bottomRight": "route_3_1_ledge_fork",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_3_1_ledge_fork",
            "roomX": 3,
            "roomY": 1,
            "x": 2,
            "y": 7,
            "type": "normal",
            "topLeft": "route_3_1_top_left_entry",
            "bottomRight": "route_3_1_bottom_fork",
            "alternative": "route_3_1_top_left_entry",
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_3_1_top_left_entry",
            "roomX": 3,
            "roomY": 1,
            "x": 0,
            "y": 7,
            "type": "exit",
            "topLeft": "route_3_1_ledge_fork",
            "bottomRight": "route_2_1_right_top_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_3_1_bottom_fork",
            "roomX": 3,
            "roomY": 1,
            "x": 7,
            "y": 19,
            "type": "normal",
            "topLeft": "route_3_1_left_entry",
            "bottomRight": "route_3_1_before_hole_fork",
            "alternative": "route_3_1_left_entry",
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_3_1_left_entry",
            "roomX": 3,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_3_1_bottom_fork",
            "bottomRight": "route_2_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_3_1_before_hole_fork",
            "roomX": 3,
            "roomY": 1,
            "x": 11,
            "y": 19,
            "type": "normal",
            "topLeft": "route_3_1_bottom_fork",
            "bottomRight": "route_3_1_bottom_jump_right",
            "alternative": "route_3_1_elevator_wait",
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 61
        },
        {
            "id": "route_3_1_bottom_jump_right",
            "roomX": 3,
            "roomY": 1,
            "x": 12,
            "y": 19,
            "type": "jump_right",
            "topLeft": "route_3_1_before_hole_fork",
            "bottomRight": "route_3_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 73
        },
        {
            "id": "route_3_1_elevator_wait",
            "roomX": 3,
            "roomY": 1,
            "x": 4,
            "y": 19,
            "type": "wait",
            "topLeft": "route_3_1_before_hole_fork",
            "bottomRight": "route_3_1_elevator_top_jump_left",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 85
        },
        {
            "id": "route_3_1_elevator_top_jump_left",
            "roomX": 3,
            "roomY": 1,
            "x": 4,
            "y": 7,
            "type": "jump_left",
            "topLeft": "route_3_1_elevator_wait",
            "bottomRight": "route_3_1_top_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 97
        },
        {
            "id": "route_3_1_right_jump_left",
            "roomX": 3,
            "roomY": 1,
            "x": 14,
            "y": 19,
            "type": "jump_left",
            "topLeft": "route_3_1_bottom_fork",
            "bottomRight": "route_3_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 109
        },
        {
            "id": "route_3_1_right_entry",
            "roomX": 3,
            "roomY": 1,
            "x": 31,
            "y": 19,
            "type": "exit",
            "topLeft": "route_3_1_right_jump_left",
            "bottomRight": "route_4_1_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_3_1.a80",
            "sourceLine": 121
        },
        {
            "id": "route_4_1_left_entry",
            "roomX": 4,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_3_1_right_entry",
            "bottomRight": "route_4_1_left_mid",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_4_1_left_mid",
            "roomX": 4,
            "roomY": 1,
            "x": 8,
            "y": 19,
            "type": "normal",
            "topLeft": "route_4_1_left_entry",
            "bottomRight": "route_4_1_left_jump",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_4_1_left_jump",
            "roomX": 4,
            "roomY": 1,
            "x": 16,
            "y": 19,
            "type": "jump_right",
            "topLeft": "route_4_1_left_mid",
            "bottomRight": "route_4_1_right_mid",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_4_1_elevator_wait",
            "roomX": 4,
            "roomY": 1,
            "x": 16,
            "y": 19,
            "type": "wait",
            "topLeft": "route_4_1_left_mid",
            "bottomRight": "route_4_1_elevator_top",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_4_1_elevator_top",
            "roomX": 4,
            "roomY": 1,
            "x": 16,
            "y": 6,
            "type": "normal",
            "topLeft": "route_4_1_elevator_wait",
            "bottomRight": "route_4_1_left_jump",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_4_1_right_mid",
            "roomX": 4,
            "roomY": 1,
            "x": 23,
            "y": 19,
            "type": "normal",
            "topLeft": "route_4_1_left_jump",
            "bottomRight": "route_4_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 61
        },
        {
            "id": "route_4_1_right_entry",
            "roomX": 4,
            "roomY": 1,
            "x": 31,
            "y": 19,
            "type": "exit",
            "topLeft": "route_4_1_right_mid",
            "bottomRight": "route_5_1_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_4_1.a80",
            "sourceLine": 73
        },
        {
            "id": "route_4_2_top_landing",
            "roomX": 4,
            "roomY": 2,
            "x": 18,
            "y": 7,
            "type": "normal",
            "topLeft": "route_4_2_slope_mid",
            "bottomRight": "route_4_2_slope_mid",
            "alternative": null,
            "sourceFile": "enemies.route_4_2.a80",
            "sourceLine": 1
        },
        {
            "id": "route_4_2_slope_mid",
            "roomX": 4,
            "roomY": 2,
            "x": 24,
            "y": 13,
            "type": "normal",
            "topLeft": "route_4_2_top_landing",
            "bottomRight": "route_4_2_slope_right",
            "alternative": null,
            "sourceFile": "enemies.route_4_2.a80",
            "sourceLine": 13
        },
        {
            "id": "route_4_2_slope_right",
            "roomX": 4,
            "roomY": 2,
            "x": 31,
            "y": 14,
            "type": "normal",
            "topLeft": "route_4_2_slope_mid",
            "bottomRight": "route_4_2_lower_right",
            "alternative": null,
            "sourceFile": "enemies.route_4_2.a80",
            "sourceLine": 25
        },
        {
            "id": "route_4_2_lower_right",
            "roomX": 4,
            "roomY": 2,
            "x": 23,
            "y": 15,
            "type": "normal",
            "topLeft": "route_4_2_slope_right",
            "bottomRight": "route_4_2_lower_left",
            "alternative": null,
            "sourceFile": "enemies.route_4_2.a80",
            "sourceLine": 37
        },
        {
            "id": "route_4_2_lower_left",
            "roomX": 4,
            "roomY": 2,
            "x": 16,
            "y": 18,
            "type": "normal",
            "topLeft": "route_4_2_lower_right",
            "bottomRight": "route_4_2_bottom_mid",
            "alternative": null,
            "sourceFile": "enemies.route_4_2.a80",
            "sourceLine": 49
        },
        {
            "id": "route_4_2_bottom_mid",
            "roomX": 4,
            "roomY": 2,
            "x": 18,
            "y": 20,
            "type": "normal",
            "topLeft": "route_4_2_lower_left",
            "bottomRight": "route_4_2_lower_left",
            "alternative": null,
            "sourceFile": "enemies.route_4_2.a80",
            "sourceLine": 61
        },
        {
            "id": "route_5_1_left_entry",
            "roomX": 5,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_4_1_right_entry",
            "bottomRight": "route_5_1_bottom_left",
            "alternative": null,
            "sourceFile": "enemies.route_5_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_5_1_bottom_left",
            "roomX": 5,
            "roomY": 1,
            "x": 8,
            "y": 19,
            "type": "normal",
            "topLeft": "route_5_1_left_entry",
            "bottomRight": "route_5_1_bottom_fork",
            "alternative": null,
            "sourceFile": "enemies.route_5_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_5_1_bottom_fork",
            "roomX": 5,
            "roomY": 1,
            "x": 16,
            "y": 19,
            "type": "normal",
            "topLeft": "route_5_1_bottom_left",
            "bottomRight": "route_5_1_bottom_right",
            "alternative": null,
            "sourceFile": "enemies.route_5_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_5_1_bottom_right",
            "roomX": 5,
            "roomY": 1,
            "x": 24,
            "y": 19,
            "type": "normal",
            "topLeft": "route_5_1_bottom_fork",
            "bottomRight": "route_5_1_right_entry",
            "alternative": null,
            "sourceFile": "enemies.route_5_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_5_1_right_entry",
            "roomX": 5,
            "roomY": 1,
            "x": 31,
            "y": 19,
            "type": "exit",
            "topLeft": "route_5_1_bottom_right",
            "bottomRight": "route_6_1_left_entry",
            "alternative": null,
            "sourceFile": "enemies.route_5_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_6_1_left_entry",
            "roomX": 6,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_5_1_right_entry",
            "bottomRight": "route_6_1_left_jump_low",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 1
        },
        {
            "id": "route_6_1_left_jump_low",
            "roomX": 6,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "jump_right",
            "topLeft": "route_6_1_left_entry",
            "bottomRight": "route_6_1_left_ledge_low",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 13
        },
        {
            "id": "route_6_1_left_ledge_low",
            "roomX": 6,
            "roomY": 1,
            "x": 4,
            "y": 17,
            "type": "jump_right",
            "topLeft": "route_6_1_left_jump_low",
            "bottomRight": "route_6_1_left_ledge_mid",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 25
        },
        {
            "id": "route_6_1_left_ledge_mid",
            "roomX": 6,
            "roomY": 1,
            "x": 5,
            "y": 14,
            "type": "jump_left",
            "topLeft": "route_6_1_left_ledge_low",
            "bottomRight": "route_6_1_left_ledge_high",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 37
        },
        {
            "id": "route_6_1_left_ledge_high",
            "roomX": 6,
            "roomY": 1,
            "x": 1,
            "y": 12,
            "type": "jump_right",
            "topLeft": "route_6_1_left_ledge_mid",
            "bottomRight": "route_6_1_red_door_left",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 49
        },
        {
            "id": "route_6_1_red_door_left",
            "roomX": 6,
            "roomY": 1,
            "x": 8,
            "y": 11,
            "type": "normal",
            "topLeft": "route_6_1_left_ledge_high",
            "bottomRight": "route_6_1_red_door_fall",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 61
        },
        {
            "id": "route_6_1_red_door_fall",
            "roomX": 6,
            "roomY": 1,
            "x": 1,
            "y": 19,
            "type": "normal",
            "topLeft": "route_6_1_red_door_left",
            "bottomRight": "route_6_1_left_return_entry",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 73
        },
        {
            "id": "route_6_1_left_return_entry",
            "roomX": 6,
            "roomY": 1,
            "x": 0,
            "y": 19,
            "type": "exit",
            "topLeft": "route_5_1_right_entry",
            "bottomRight": "route_6_1_red_door_fall",
            "alternative": null,
            "sourceFile": "enemies.route_6_1.a80",
            "sourceLine": 85
        }
    ],
    "rewires": [
        {
            "from": "route_1_1_left_inner",
            "field": "topLeft",
            "to": "route_1_1_left_jump_right",
            "sourceFile": "logic/room1_1.a80",
            "sourceLine": 16,
            "routine": "activate_glass_route"
        },
        {
            "from": "route_1_1_right_mid",
            "field": "topLeft",
            "to": "route_1_1_right_jump_left",
            "sourceFile": "logic/room1_1.a80",
            "sourceLine": 22,
            "routine": "activate_glass_route"
        },
        {
            "from": "route_2_0_top_mid",
            "field": "bottomRight",
            "to": "route_2_0_basement_entry",
            "sourceFile": "logic/room2_0.a80",
            "sourceLine": 19,
            "routine": "activate_roof_route"
        },
        {
            "from": "route_4_1_left_mid",
            "field": "alternative",
            "to": "route_4_1_elevator_wait",
            "sourceFile": "logic/room4_1.a80",
            "sourceLine": 3,
            "routine": "activate_elevator_wait_route"
        }
    ]
};
